server:
  port: 8080

  servlet:
    session:
      timeout: ${STUDENT_VERIFICATION_SESSION_TIME:1m}

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY:S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_ACCESS_KEY:S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_BUCKET_NAME:s3-bucket}
      url:
        prefix: "https://${AWS_S3_BUCKET_NAME:s3-bucket}.s3.ap-northeast-2.amazonaws.com"

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui.display-request-duration: true
  swagger-ui:
    path: /docs/swagger

zupzup:
  auth:
    jwt:
      access:
        secret: ${ACCESS_TOKEN_SECRET_KEY:accessFSFvPh5v9x3w+T8fA9gB7eC6dF3gH5jJ2kL4mN1oP0rS1c}
        expiration-second: ${ACCESS_TOKEN_EXPIRATION:6000}  # 초 단위
